title: Good things
author: Obiora
email: obioramaduakor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog talking about good things.

# social links
twitter_username: Obiora_M # DO NOT include the @ character, or else the build will fail!
github_username:  ObioraM # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
